// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkj8Jp_Nb91GYK7s9E-zgOZgMtkjuyBRc',
    appId: '1:963291463067:web:853e0d5d4cc2400374f53e',
    messagingSenderId: '963291463067',
    projectId: 'assignmentauth-557ba',
    authDomain: 'assignmentauth-557ba.firebaseapp.com',
    storageBucket: 'assignmentauth-557ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0Uyo5wYb7vEvwtejHF3_7O6R3qhOPGM',
    appId: '1:963291463067:android:e2cedc42752b65e974f53e',
    messagingSenderId: '963291463067',
    projectId: 'assignmentauth-557ba',
    storageBucket: 'assignmentauth-557ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaeB8HhUoQl6KSB3EuxS48jhnCiGBUbEE',
    appId: '1:963291463067:ios:0bb4e36e9567a28f74f53e',
    messagingSenderId: '963291463067',
    projectId: 'assignmentauth-557ba',
    storageBucket: 'assignmentauth-557ba.appspot.com',
    androidClientId: '963291463067-82ui2jhcgigmdjebd4hbn1rjui46antu.apps.googleusercontent.com',
    iosClientId: '963291463067-2qnun29im9b4ord3o160uc4abnni43vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaeB8HhUoQl6KSB3EuxS48jhnCiGBUbEE',
    appId: '1:963291463067:ios:bc2d42b4937e4fba74f53e',
    messagingSenderId: '963291463067',
    projectId: 'assignmentauth-557ba',
    storageBucket: 'assignmentauth-557ba.appspot.com',
    androidClientId: '963291463067-82ui2jhcgigmdjebd4hbn1rjui46antu.apps.googleusercontent.com',
    iosClientId: '963291463067-p9esh3jeuae0u17q5vqp28ooleogcpje.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
